version: "3.8"
services:
  rest-user:
    # image: gestiondeprojet-loginapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rest-user
    ports:
      - "8081:8081"
  login:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: login
    ports:
      - "8082:8081"

